# Generated by Django 6.0 on 2025-12-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfmApp", "0002_incomedb_delete_income"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomedb",
            name="Date",
            field=models.DateField(db_index=True),
        ),
    ]
