# Generated by Django 6.0 on 2026-01-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfmApp", "0005_commitmentdb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commitmentdb",
            name="is_recurring",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
