# Generated by Django 6.0 on 2026-01-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pfmApp", "0007_savingsdb"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expensedb",
            old_name="Amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="expensedb",
            old_name="Category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="expensedb",
            old_name="Date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="expensedb",
            old_name="Expense_title",
            new_name="expense_title",
        ),
        migrations.RenameField(
            model_name="expensedb",
            old_name="Note",
            new_name="note",
        ),
        migrations.RenameField(
            model_name="expensedb",
            old_name="User",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="incomedb",
            old_name="Amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="incomedb",
            old_name="Date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="incomedb",
            old_name="Income_source",
            new_name="income_source",
        ),
        migrations.RenameField(
            model_name="incomedb",
            old_name="Note",
            new_name="note",
        ),
        migrations.RenameField(
            model_name="incomedb",
            old_name="User",
            new_name="user",
        ),
    ]
