# Generated by Django 6.0 on 2026-03-13 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfmApp", "0008_rename_amount_expensedb_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensedb",
            name="category",
            field=models.CharField(
                choices=[
                    ("needs", "Needs"),
                    ("wants", "Wants"),
                    ("growth", "Growth"),
                    ("commitment", "Commitment"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="savingsdb",
            name="category",
            field=models.CharField(
                choices=[
                    ("safety", "Safety Fund"),
                    ("future_freedom", "Future Freedom"),
                    ("goal", "Goal Saving"),
                    ("investment", "Investment Fund"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ExpenseSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                ("period", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
