# Generated by Django 6.0 on 2026-03-13 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfmApp", "0009_alter_expensedb_category_alter_savingsdb_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensedb",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="pfmApp.expensesubcategory",
            ),
        ),
    ]
